### ISSUE TITLE
Double-line when inspector collapsed

### ISSUE THREAD

**Issue by mdk** [JustSid/JUInspectorView#1]
When two inspectors are collapsed, the bottom line of the first one (1px gray) + the top line of the second one (1px gray) effectively produces a 2px line effect:

![Double line](http://files.mdk.am/screenshots/double-line.png)

Xcode4 somehow manages that correctly:

![Single line](http://files.mdk.am/screenshots/single-line.png)

Ideally the inspectors should be moved 1px up/down when collapsed... or something. 

BTW, thanks for great work.

**Comment by JustSid** [comment]
Thanks for finding this!
